qingcha:
  rpc:
    client:
      package-path: com.qingcha.rpc.examples.spring.service
      host: localhost
      port: 9900
    server:
      port: 9900
      # 可换成自定义注解
      service-annotation: org.springframework.stereotype.Service
logging:
  level:
    com.qingcha.rpc: debug
